import { NextRequest, NextResponse } from 'next/server';
import type { HelpSearchResult, HelpSearchResponse } from '@/lib/types';

// Mock FAQ database
const faqs: HelpSearchResult[] = [
  {
    type: 'faq',
    category: 'Getting Started',
    question: 'How do I install the Clarityflow SDK?',
    answer:
      'You can install our SDK via npm with `npm install @clarityflow/sdk` or include our script tag directly in your HTML. See our Getting Started guide for detailed instructions.',
  },
  {
    type: 'faq',
    category: 'Getting Started',
    question: 'How long does setup take?',
    answer:
      'Most teams are up and running within 15 minutes. Our SDK auto-tracks page views and basic events. Custom event tracking takes a bit more time depending on your needs.',
  },
  {
    type: 'faq',
    category: 'Billing',
    question: 'How does usage-based billing work?',
    answer:
      'You are billed based on the number of unique tracked users per month. Each plan includes a base number of users, with additional users billed at a per-user rate.',
  },
  {
    type: 'faq',
    category: 'Billing',
    question: 'Can I change my plan mid-cycle?',
    answer:
      'Yes! You can upgrade or downgrade at any time. Changes are prorated based on your remaining billing cycle.',
  },
  {
    type: 'faq',
    category: 'Data & Privacy',
    question: 'Is Clarityflow GDPR compliant?',
    answer:
      'Yes, we are fully GDPR compliant. We offer data processing agreements (DPAs) and can help you configure consent-based tracking.',
  },
  {
    type: 'faq',
    category: 'Data & Privacy',
    question: 'Where is my data stored?',
    answer:
      'All data is stored in SOC 2 Type II certified data centers. We offer both US and EU data residency options.',
  },
  {
    type: 'faq',
    category: 'Integration',
    question: 'What integrations do you support?',
    answer:
      'We integrate with Slack, Segment, Google Analytics, Mixpanel, and many more. Check our integrations page for the full list.',
  },
  {
    type: 'faq',
    category: 'Features',
    question: 'What are AI insights?',
    answer:
      'AI insights are plain-English recommendations generated by our machine learning models. They tell you exactly what to fix and how to prioritize improvements.',
  },
];

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const query = searchParams.get('q')?.toLowerCase() || '';

  // Simulate search latency
  await new Promise((resolve) => setTimeout(resolve, 100));

  let results: HelpSearchResult[] = [];

  if (query.length > 0) {
    results = faqs.filter(
      (faq) =>
        faq.question?.toLowerCase().includes(query) ||
        faq.answer?.toLowerCase().includes(query) ||
        faq.category.toLowerCase().includes(query)
    );
  } else {
    // Return all FAQs if no query
    results = faqs;
  }

  const response: HelpSearchResponse = {
    results,
    query,
    total: results.length,
  };

  return NextResponse.json(response);
}
